[profile.default]
solc_version = "0.8.20"
src = 'src'
out = 'out'
libs = ['lib']

fs_permissions = [{ access = "read-write", path = "./" }]


remappings = ['@openzeppelin/=lib/openzeppelin-contracts/']


[rpc_endpoints]
mordor = "${RPC_MORDOR}"
